# Generated by Django 6.0.4 on 2026-06-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='city',
            field=models.CharField(default='mumbai', max_length=100),
        ),
    ]
