# Generated by Django 6.0.4 on 2026-06-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_reg_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg',
            old_name='adress',
            new_name='address',
        ),
    ]
